version: "3"
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "4001:4001"
    volumes:
      - .:/ecom/backend
    command: ["npm", "run", "dev"]

volumes:
  mongodb-data:
